version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    groups:
      expo-updates:
        patterns:
          - "expo*"
          - "@expo/*"
        update-types:
          - "minor"
          - "patch"
      react-updates:
        patterns:
          - "react*"
          - "@react-*"
        update-types:
          - "minor"
          - "patch"
      sentry-updates:
        patterns:
          - "@sentry/*"
        update-types:
          - "minor"
          - "patch"