name: Delete closed branches

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.head.ref != 'main'
    steps:
      - uses: peter-evans/delete-branch@v5
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
