name: Delete merged branches

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/delete-branch@v5
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
